# Generated by Django 4.1.2 on 2022-10-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=1000)),
                ('hospital_name', models.CharField(max_length=1000)),
                ('price', models.IntegerField(max_length=1000)),
                ('image_url', models.CharField(max_length=10000)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
