# Generated by Django 4.1.2 on 2022-10-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='highlight',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='query',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.query'),
            preserve_default=False,
        ),
    ]
