# Generated by Django 4.1.2 on 2022-10-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_query_hospital_highlight_hospital_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=1000)),
                ('price', models.IntegerField(max_length=10000)),
                ('image_url', models.CharField(max_length=100000)),
                ('highlights', models.TextField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.query')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
