# Generated by Django 4.1.2 on 2022-10-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hospital_medicalservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='price',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='price',
            field=models.CharField(max_length=10000),
        ),
    ]
